routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function(){

    Route::get('/my-account', 'AccountController@myAccount')->name('my.account');
    Route::post('/update-account', 'AccountController@updateMyAccount')->name('update.account');

    Route::resource('/contacts', 'ContactController');
    Route::post('/contacts/search', 'ContactController@search')->name('contact.search');

});

app/Contact.php
<?php

namespace App;
use Illuminate\Database\Eloquent\SoftDeletes; 
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use SoftDeletes;
    protected $guarded=[];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/helpers.php
<?php

use Illuminate\Support\Facades\Session;


function flashMessage($msg='Data has been saved.', $type='success')
{
   Session::flash('flash_data',array('msg'=>$msg, 'type'=>$type));
}


function getFlashMessage(){

  $alert_type = 'alert-success';

  $flash_data = Session::get('flash_data');
  
  if($flash_data != null){

    if ($flash_data['type'] == 'success') {
       $alert_type = 'alert-success';
    }

    elseif($flash_data['type'] == 'warning'){
        $alert_type = 'alert-warning';
    }

    elseif($flash_data['type'] == 'error'){
        $alert_type = 'alert-danger';
    }

    elseif($flash_data['type'] == 'info'){
        $alert_type = 'alert-info';
    }

    echo      '<div class="alert '. $alert_type .' alert-dismissible fade show text-center" role="alert" style="opacity: 1; border-radius: 0; margin: 10px 0px;">'
                .$flash_data['msg'].
              '<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span style="color: #fff;" aria-hidden="true">&times;</span>
              </button>
              </div>';
  }
  
  return null;
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AccountController extends Controller
{
    public function myAccount()
    {
        $my_account = Auth::user();
        return view('account.profile', compact('my_account'));
    }

    public function updateMyAccount(Request $request)
    {
        $user = Auth::user();
        $validated_data = $request->validate([
            'name'        => 'required',
            'password'    => 'required',
        ]);

        $user->name = $validated_data['name'];
        $user->password = bcrypt($validated_data['password']);
        $user->save();

        flashMessage('Account has been updated');
        return back();
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Mail\SendEmailToNewContact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class ContactController extends Controller
{

    public function search(Request $request)
    {
        $keyword = $request->search;
        $contacts = Contact::where('first_name','like',"%$keyword%")
                           ->orWhere('last_name','like',"%$keyword%")
                           ->orWhere('email','like',"%$keyword%")
                           ->paginate(10);

        return view('contacts.index',compact('contacts'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::paginate(10);
        // dd($contacts);
        return view('contacts.index',compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $contact = new Contact();
        return view('contacts.create', compact('contact'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated_data = $request->validate([
            'first_name'        => 'required',
            'last_name'         => 'required',
            'email'             => 'required|email|unique:contacts',
            'contact_number'    => 'required',
        ]);
       
        $contact = Contact::create($validated_data);

        Mail::to($contact->email)->send(new SendEmailToNewContact());

        flashMessage('Contact has been saved.');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        return view('contacts.show', compact('contact'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        return view('contacts.create', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
    
        $validated_data = $request->validate([
            'first_name'        => 'required',
            'last_name'         => 'required',
            'email'             => 'required|email|unique:contacts,email,' . $contact->id,
            'contact_number'    => 'required',
        ]);

        
        
        Contact::where('id', $contact->id)->update($validated_data);

        flashMessage("Contact updated");

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        return redirect()->route('contacts.index');
    }

   
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return redirect()->route('contacts.index');
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <section class="row">

            <div class="col-md-8 mx-auto">
    
                <div class="card">

                    <div class="card-header">
                      Create New Contact
                    </div>

                    <div class="card-body">

                        {{ getFlashMessage() }}


                        <form action="{{ $contact->id !=null ? route('contacts.update', $contact) : route('contacts.store') }}" method="post">
                            
                            @if ($contact->id != null)
                                @method('PUT')
                            @endif

                            @csrf

                            <div class="form-group">
                                <label for="first_name">First Name</label>
                                <input type="text" class="form-control" value="{{ $contact->first_name }}" name="first_name" id="first_name" required>
                            </div>

                            <div class="form-group">
                                <label for="last_name">Last Name</label>
                                <input type="text" class="form-control" value="{{ $contact->last_name }}" name="last_name" id="last_name" required>
                            </div>

                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" value="{{ $contact->email }}" name="email" id="email" required>
                            </div>

                            <div class="form-group">
                                <label for="contact_number">Contact Number</label>
                                <input type="text" class="form-control" value="{{ $contact->contact_number }}" name="contact_number" id="contact_number" required>
                            </div>

                            <div class="form-group">
                                <a href="{{ route('contacts.index') }}" class="btn btn-dark">Back to List</a>
                                <input type="submit" class="btn btn-dark" value="{{ $contact->id != null ? 'Update' : 'Create'}}">
                            </div>

                        </form>

                    </div>

                </div>

            </div>

        </section>

    </div>    

@endsection

resources/views/contacts/emailNotif.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>New Contact</title>
  </head>
  <body>
    <h1>We added you in our contact list. Thank you.</h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <section class="row">
            
            <div class="col">
    
                <div class="card">

                    <div class="card-header">
                        Contact List
                    </div>
            
                    <div class="card-body">
            
                        <div>
                            <div class="row">
                                <div class="col">
                                    <a href="{{ route('contacts.create') }}" class="btn btn-dark mb-3">Create New Contact</a>
                                </div>
                                <div class="col text-right">
                                    
                                    <form action="{{ route('contact.search') }}" method="post">
                                        
                                        @csrf
                                       
                                       <div class="row no-gutters d-flex justify-content-end">
            
                                           <div class="col-5">
                                                <input type="text" name="search" class="form-control">
                                           </div>
            
                                           <div class="col-auto">
                                               <input type="submit" value="Search" class="btn btn-dark btn-small ml-1">
                                           </div>
                                           
                                       </div>
            
                                    </form>
                                    
                                </div>
                            </div>
                            
                            
                        </div>
            
                        <div class="table-responsive">
            
                            <table class="table">
            
                                <thead class="">
                                    <tr>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Email</th>
                                        <th>Contact Number</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
            
                                <tbody>
                                   
                                   @foreach ($contacts as $contact)
                                    <tr>
                                        <td>{{ $contact->first_name }}</td>
                                        <td>{{ $contact->last_name }}</td>
                                        <td>{{ $contact->email }}</td>
                                        <td>{{ $contact->contact_number }}</td>
                                        <td>
                                            <a href="{{ route('contacts.edit', $contact) }}">Edit</a> |
               
                                            <a href="{{ route('contacts.show', $contact) }}">View</a>
                                        </td>
                                    </tr>
                                   @endforeach
                                    
                                </tbody>
            
                            </table>
            
                        </div>
            
                        
            
                    </div>
                </div>

                <div class="mt-2 text-center">
                    {{ $contacts->links() }}
                </div>

            </div>


           

        </section>

    </div>    

@endsection

resources/views/contacts/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <section class="row">

            <div class="col-md-8 mx-auto">
    
                <div class="card">

                    <div class="card-header">
                      View Contact
                    </div>

                    <div class="card-body">

                        {{ getFlashMessage() }}


                       
                            
                            @method('PUT')

                            @csrf

                            <div class="form-group">
                                <label for="first_name">First Name</label>
                                <input type="text" class="form-control" value="{{ $contact->first_name }}" name="first_name" id="first_name" readonly>
                            </div>

                            <div class="form-group">
                                <label for="last_name">Last Name</label>
                                <input type="text" class="form-control" value="{{ $contact->last_name }}" name="last_name" id="last_name" readonly>
                            </div>

                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" value="{{ $contact->email }}" name="email" id="email" readonly>
                            </div>

                            <div class="form-group">
                                <label for="contact_number">Contact Number</label>
                                <input type="text" class="form-control" value="{{ $contact->contact_number }}" name="contact_number" id="contact_number" readonly>
                            </div>

                            <div class="form-group">
                                <a href="{{ route('contacts.index') }}" class="btn btn-dark">Back to List</a>
                                <input type="submit" class="btn btn-dark" data-toggle="modal" data-target="#exampleModal" value="Delete Contact">
                            </div>

                      

                    </div>

                </div>

            </div>

        </section>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document" style="width: 500px; max-width: 500px;">
            <div class="modal-content">
                <div class="modal-header">
                
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body d-flex align-items-center justify-content-center" style="height: 150px;">
                    <h5 class="modal-title" id="exampleModalLabel">Contact will be deleted</h5>
                </div>
                <div class="modal-footer">
                <span class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</span>

                
                <form action="{{ route('contacts.destroy', $contact) }}" method="post">
                    @method("DELETE")
                    @csrf
                    <input class="btn btn-secondary btn-sm text-white" type="submit" value="Proceed">

                </form>
                </div>
            </div>
            </div>
        </div>

    </div>    

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->

                        

                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item mr-3">
                                <a class="nav-link" href="{{ route('contacts.index') }}">Contacts</a>
                            </li> 
                            
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('my.account') }}">
                                        My Account
                                    </a>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>